CREATE DATABASE Filmes;
GO

USE Filmes
GO

CREATE TABLE Genero(
	IdGenero INT PRIMARY KEY IDENTITY,
	NomeGenero VARCHAR(200) NOT NULL
);
GO

CREATE TABLE Filme(
	IdFilme INT PRIMARY KEY IDENTITY,
	NomeFilme VARCHAR(200) NOT NULL,
	DataLancamento DATE NOT NULL,
	Diretor VARCHAR(200) NOT NULL,
	IdGenero INT FOREIGN KEY REFERENCES Genero(IdGenero)
);
GO

CREATE TABLE Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(200) NOT NULL,
	Email VARCHAR(200) NOT NULL,
	Senha VARCHAR(200) NOT NULL,
	AdminUser BIT DEFAULT 0 NOT NULL,
);
GO