CREATE DATABASE Locadora;

USE Locadora;

CREATE TABLE Cliente (
	IdCliente INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(200),
	CPF BIGINT
);

CREATE TABLE Empresa (
	IdEmpresa INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(200)
);

CREATE TABLE Marca(
	IdMarca INT PRIMARY KEY IDENTITY NOT NULL,
	Nome VARCHAR(200),
);

CREATE TABLE Modelo(
	IdModelo INT PRIMARY KEY IDENTITY NOT NULL,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca),
	Nome VARCHAR(200)
);

CREATE TABLE Veiculo (
	IdVeiculo INT PRIMARY KEY IDENTITY NOT NULL,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa),
	IdModelo INT FOREIGN KEY REFERENCES Modelo (IdModelo),
);

CREATE TABLE Aluguel(
	IdAluguel INT PRIMARY KEY IDENTITY NOT NULL,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente),
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo (IdVeiculo),
	DataInicio DATE
	DataFim DATE
);
